SELECT COUNT(*) FROM BOOKING_DNORM;
SELECT COUNT(*) FROM REGULAR_BOOKING_DNORM;
SELECT COUNT(*) FROM SHIFT_DNORM;
SELECT COUNT(*) FROM CARS_DNORM;
SELECT COUNT(*) FROM DRIVER_REVENUE_DNORM;
SELECT COUNT(*) FROM EMPLOYEE_INCIDENTS_DNORM;
SELECT COUNT(*) FROM CLIENTS_DNORM;

SELECT COUNT(*) FROM BOOKING_DNORM_BIG;
SELECT COUNT(*) FROM REGULAR_BOOKING_DNORM_BIG;
SELECT COUNT(*) FROM SHIFT_DNORM_BIG;
SELECT COUNT(*) FROM CARS_DNORM_BIG;
SELECT COUNT(*) FROM DRIVER_REVENUE_DNORM_BIG;
SELECT COUNT(*) FROM EMPLOYEE_INCIDENTS_DNORM_BIG;
SELECT COUNT(*) FROM CLIENTS_DNORM_BIG;