/* DROP STATEMENTS */ 
DROP TABLE RECURRENT_BOOKING;
DROP TABLE PAYMENT;
DROP TABLE CORPORATE_CLIENT;
DROP TABLE REGULAR_BOOKING;
DROP TABLE CLIENTS;
DROP TABLE CARS;
DROP TABLE DRIVER_REVENUE;
DROP TABLE BOOKING;
DROP TABLE DRIVER;
DROP TABLE PAY_TYPE;
DROP TABLE OPERATOR;
DROP TABLE EMPLOYEE_INCIDENTS;
DROP TABLE SHIFT;
DROP TABLE EMPLOYEE;
DROP TABLE CITY_LOOKUP;

/* Normalised Table Minus some constraints to make increasing the size exponetially easier */
/* CITY_LOOKUP Table */ 
CREATE TABLE CITY_LOOKUP(
POSTCODE VARCHAR(8) PRIMARY KEY,
CITY VARCHAR(50)
);

/* CLIENTS Table */ 
CREATE TABLE CLIENTS (
CLIENTID CHAR(9) PRIMARY KEY,
CLIENTTYPE VARCHAR(15),
CONTACTFNAME VARCHAR(255),
CONTACTLNAME VARCHAR(255),
PPHONENO CHAR(11),
SPHONENO CHAR(11),
EMAIL VARCHAR2(400)
);

/* PAY_TYPE Table */ 
CREATE TABLE PAY_TYPE (
PAYTYPE VARCHAR(9) PRIMARY KEY,
PAYVALUE NUMBER(9)   
);

/* EMPLOYEE Table */ 
CREATE TABLE EMPLOYEE(
NINUMBER CHAR(9) PRIMARY KEY, 
POSTCODE VARCHAR(20), 
ADDRESS VARCHAR2(255), 
FIRSTNAME VARCHAR(255), 
LASTNAME VARCHAR(255), 
PPHONENO CHAR(11),
SPHONENO CHAR(11),
SEX CHAR(1),
DOB DATE, 
EMAIL VARCHAR2(255), 
HIREDATE DATE
);

/* OPERATOR Table */ 
CREATE TABLE OPERATOR (
OPERATORID CHAR(9),
EMPLOYEEID CHAR(9),
SALARY NUMBER(8,2),
TAXCODE VARCHAR(20)
); 

/* DRIVER Table */ 
CREATE TABLE DRIVER (
DRIVERLICENSEID CHAR(9),
EMPLOYEEID CHAR(9),
PAYTYPE VARCHAR (9)
);

/* BOOKING Table */ 
CREATE TABLE BOOKING (
BOOKINGID CHAR(9) PRIMARY KEY,
OPERATORID CHAR(9),
DRIVERID CHAR(9),
DATEBOOKED DATE,
PICKUPDATE DATE,
PICKUPADDRESS VARCHAR(255),
DROPOFFADDRESS VARCHAR2(255),
NOOFPASSENGERS NUMBER(2),
CUSTOMERPHONENUMBER CHAR(11)
);

/* REGULAR_BOOKING Table */ 
CREATE TABLE REGULAR_BOOKING(
REGBOOKID CHAR(9) PRIMARY KEY,
CLIENTID CHAR(9),
BOOKINGFREQUENCY VARCHAR(50),
STARTDATE DATE,
NOOFTRANSPORTEES NUMBER(2),
DURATION VARCHAR(10)
);

/* DRIVER_REVENUE Table */ 
CREATE TABLE DRIVER_REVENUE(
REVENUEID CHAR(9) PRIMARY KEY,
DRIVERID CHAR(9),
REVENUEDATE DATE,
GROSSTAKINGS NUMBER(8,2),
PAIDTOCOMPANY NUMBER(8,2),
NETEARNINGS NUMBER(8,2)
);

/* CORPERATE_CLIENT Table */ 
CREATE TABLE CORPORATE_CLIENT (
CLIENTID CHAR(9) PRIMARY KEY,
CORPERATIONNAME VARCHAR(50)
);

/* EMPLOYEE_INCIDENTS Table */ 
CREATE TABLE EMPLOYEE_INCIDENTS (
INCIDENTID CHAR(9) PRIMARY KEY,
NINUMBER CHAR(9),
INCIDENTTYPE VARCHAR2(20),
INCIDENTNOTES VARCHAR2(4000),
INCIDENTDATE DATE
);

/* CARS Table */ 
CREATE TABLE CARS (
REGISTRATIONNO CHAR(7) PRIMARY KEY,
DRIVERID CHAR(9),
REGISTRATIONYEAR INTEGER,
MILEAGE VARCHAR(10),
LASTMOTDATE DATE,
NOOFSEATS VARCHAR(10),
CARSTATUS VARCHAR(30),
OWNERID VARCHAR(9)
);

/* SHIFT Table */ 
CREATE TABLE SHIFT (
SHIFTID CHAR(9) PRIMARY KEY,
EMPLOYEEID CHAR(9),
SHIFTDATE DATE,
SHIFTTYPE VARCHAR(20)
);

/* PAYMENT Table */ 
CREATE TABLE PAYMENT (
PAYMENTID CHAR(9) PRIMARY KEY,
BOOKINGID CHAR(9),
PAYMENTMETHOD VARCHAR(10),
PAYMENTDATE DATE,
PAYEESFIRSTNAME VARCHAR(255),
PAYEESLASTNAME VARCHAR(255),
CARDNUMBER VARCHAR(16),
EXPIRYDATE DATE,
CVV CHAR(3),
AMOUNTPAID NUMBER(8,2)
);

/* RECURRENT_BOOKING Table */ 
CREATE TABLE RECURRENT_BOOKING (
BOOKINGID CHAR(9),
REGBOOKID CHAR(9)
);