/* RECURRENT_BOOKING Inserts */ 
INSERT INTO RECURRENT_BOOKING VALUES('BK0000002','RB0000001');
INSERT INTO RECURRENT_BOOKING VALUES('BK0000003','RB0000002');
INSERT INTO RECURRENT_BOOKING VALUES('BK0000004','RB0000003');

/* BIG TABLES (Normalized) */
DROP TABLE REGULAR_BOOKING_BIG;
DROP TABLE CLIENTS_BIG;
DROP TABLE CARS_BIG;
DROP TABLE DRIVER_REVENUE_BIG;
DROP TABLE BOOKING_BIG;
DROP TABLE EMPLOYEE_INCIDENTS_BIG;
DROP TABLE SHIFT_BIG;
DROP TABLE EMPLOYEE_BIG;

DROP TABLE RECURRENT_BOOKING_BIG;
DROP TABLE PAY_TYPE_BIG;
DROP TABLE DRIVER_BIG;
DROP TABLE OPERATOR_BIG;
DROP TABLE  CITY_LOOKUP_BIG;
DROP TABLE CORPORATE_CLIENT_BIG;
DROP TABLE PAYMENT_BIG;

CREATE TABLE REGULAR_BOOKING_BIG AS SELECT * FROM REGULAR_BOOKING;
CREATE TABLE CLIENTS_BIG AS SELECT * FROM CLIENTS;
CREATE TABLE CARS_BIG AS SELECT * FROM CARS;
CREATE TABLE DRIVER_REVENUE_BIG AS SELECT * FROM DRIVER_REVENUE;
CREATE TABLE BOOKING_BIG AS SELECT * FROM BOOKING;
CREATE TABLE EMPLOYEE_INCIDENTS_BIG AS SELECT * FROM EMPLOYEE_INCIDENTS;
CREATE TABLE SHIFT_BIG AS SELECT * FROM SHIFT;
CREATE TABLE EMPLOYEE_BIG AS SELECT * FROM EMPLOYEE;

CREATE TABLE RECURRENT_BOOKING_BIG AS SELECT * FROM RECURRENT_BOOKING;
CREATE TABLE PAY_TYPE_BIG AS SELECT * FROM PAY_TYPE;
CREATE TABLE DRIVER_BIG AS SELECT * FROM DRIVER;
CREATE TABLE OPERATOR_BIG AS SELECT * FROM OPERATOR;
CREATE TABLE CITY_LOOKUP_BIG AS SELECT * FROM CITY_LOOKUP;
CREATE TABLE CORPORATE_CLIENT_BIG AS SELECT * FROM CORPORATE_CLIENT;
CREATE TABLE PAYMENT_BIG AS SELECT * FROM PAYMENT;

/* INCREASE EXPONENTIALLY (Normalized) */
SET SERVEROUTPUT ON;

DECLARE
cntr NUMBER := 0;
BEGIN
    FOR loop_counter IN 1..13 
LOOP
cntr := cntr  + 1;
INSERT INTO BOOKING_BIG SELECT * FROM BOOKING_BIG;
INSERT INTO REGULAR_BOOKING_BIG SELECT * FROM REGULAR_BOOKING_BIG;
INSERT INTO SHIFT_BIG SELECT * FROM SHIFT_BIG;
INSERT INTO CARS_BIG SELECT * FROM CARS_BIG;
INSERT INTO DRIVER_REVENUE_BIG SELECT * FROM DRIVER_REVENUE_BIG;
INSERT INTO EMPLOYEE_INCIDENTS_BIG SELECT * FROM EMPLOYEE_INCIDENTS_BIG;
INSERT INTO CLIENTS_BIG SELECT * FROM CLIENTS_BIG;

INSERT INTO RECURRENT_BOOKING_BIG SELECT * FROM RECURRENT_BOOKING_BIG;
INSERT INTO PAY_TYPE_BIG SELECT * FROM PAY_TYPE_BIG ;
INSERT INTO DRIVER_BIG SELECT * FROM DRIVER_BIG;
INSERT INTO CITY_LOOKUP_BIG SELECT * FROM CITY_LOOKUP_BIG;
INSERT INTO CORPORATE_CLIENT_BIG SELECT * FROM CORPORATE_CLIENT_BIG;
INSERT INTO OPERATOR_BIG  SELECT * FROM OPERATOR_BIG;
INSERT INTO PAYMENT_BIG SELECT * FROM PAYMENT_BIG;
INSERT INTO EMPLOYEE_BIG SELECT * FROM EMPLOYEE_BIG;

END LOOP;
dbms_output.put_line('Executed: ' || cntr) ;
END;
/