SET TIMING ON
SET AUTOTRACE TRACEONLY

/* FIRST RUN */
SELECT EMPLOYEE_BIG.FIRSTNAME || ' ' || EMPLOYEE_BIG.LASTNAME AS "Employee Name", EMPLOYEE_INCIDENTS_BIG.IncidentType, EMPLOYEE_INCIDENTS_BIG.IncidentNotes, EMPLOYEE_INCIDENTS_BIG.IncidentDate, CITY_LOOKUP_BIG.PostCode, CITY_LOOKUP_BIG.City
FROM EMPLOYEE_INCIDENTS_BIG, CITY_LOOKUP_BIG, EMPLOYEE_BIG
WHERE EMPLOYEE_INCIDENTS_BIG.NINumber = EMPLOYEE_BIG.NINumber 
AND CITY_LOOKUP_BIG.POSTCODE = EMPLOYEE_BIG.POSTCODE
AND (CITY_LOOKUP_BIG.PostCode LIKE 'N%' OR
CITY_LOOKUP_BIG.PostCode LIKE 'NW%' OR
CITY_LOOKUP_BIG.PostCode LIKE 'SW%' OR CITY_LOOKUP_BIG.PostCode LIKE 'W%');

/* SECOND RUN */
DROP INDEX EMPLOYEE_INDEX;
DROP INDEX CITY_LOOKUP_INDEX;
DROP INDEX EMPLOYEE_INCIDENTS_INDEX;

CREATE INDEX EMPLOYEE_INDEX ON EMPLOYEE_BIG (NINUMBER, POSTCODE);
CREATE INDEX CITY_LOOKUP_INDEX ON CITY_LOOKUP_BIG (POSTCODE);
CREATE INDEX EMPLOYEE_INCIDENTS_INDEX ON EMPLOYEE_INCIDENTS_BIG (NINUMBER);

SELECT EMPLOYEE_BIG.FIRSTNAME || ' ' || EMPLOYEE_BIG.LASTNAME AS "Employee Name", EMPLOYEE_INCIDENTS_BIG.IncidentType, EMPLOYEE_INCIDENTS_BIG.IncidentNotes, EMPLOYEE_INCIDENTS_BIG.IncidentDate, CITY_LOOKUP_BIG.PostCode, CITY_LOOKUP_BIG.City
FROM EMPLOYEE_INCIDENTS_BIG, CITY_LOOKUP_BIG, EMPLOYEE_BIG
WHERE EMPLOYEE_INCIDENTS_BIG.NINumber = EMPLOYEE_BIG.NINumber 
AND CITY_LOOKUP_BIG.POSTCODE = EMPLOYEE_BIG.POSTCODE
AND (CITY_LOOKUP_BIG.PostCode LIKE 'N%' OR
CITY_LOOKUP_BIG.PostCode LIKE 'NW%' OR
CITY_LOOKUP_BIG.PostCode LIKE 'SW%' OR CITY_LOOKUP_BIG.PostCode LIKE 'W%');
